@startuml

title __PNIMIYAPP's Class Diagram__\n

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.AddPostFragment {

    }
  }
  

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.AddUserFragment {

    }
  }
  

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.AdminPageFragment {

    }
  }
  

  

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.AttendanceFragment {

    }
  }
  

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.AttendanceHistoryFragment {

    }
  }
  

  

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.ChangeUserSettings {

    }
  }


  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.Home {

    }
  }
  

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.HomeFragment {

    }
  }


  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.IdeaBoxFragment {

    }
  }
  

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.InstagramFragment {

    }
  }


  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.ListChangeUser {

    }
  }
  


  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.Login {

    }
  }
  

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.PhoneBookFragment {

    }
  }
  

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.RequestsFragment {

    }
  }
  

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.RestorePasswordActivity {

    }
  }
  

  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.ScheduleFragment {

    }
  }
  


  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.SendCodeRestorePasswordActivity {

    }
  }
  


  namespace com.lipstudio.pnimiyapp {
    class com.lipstudio.pnimiyapp.SingleAttendanceHistory {

    }
  }
  

  

  com.lipstudio.pnimiyapp.AddPostFragment -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.AddUserFragment -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.AdminPageFragment -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.AttendanceFragment -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.AttendanceHistoryFragment -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.ChangeUserSettings -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.Home -up-|> androidx.appcompat.app.AppCompatActivity
  com.lipstudio.pnimiyapp.HomeFragment -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.IdeaBoxFragment -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.InstagramFragment -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.ListChangeUser -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.Login -up-|> androidx.appcompat.app.AppCompatActivity
  com.lipstudio.pnimiyapp.PhoneBookFragment -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.RequestsFragment -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.RestorePasswordActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.lipstudio.pnimiyapp.ScheduleFragment -up-|> androidx.fragment.app.Fragment
  com.lipstudio.pnimiyapp.SendCodeRestorePasswordActivity -up-|> androidx.appcompat.app.AppCompatActivity
  com.lipstudio.pnimiyapp.SingleAttendanceHistory -up-|> androidx.fragment.app.Fragment

right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
